# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'rspec', all_after_pass: false, :version => 2 do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$}) { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^views/(.+)\.erb$}) { |m| "spec/#{m[1]}_spec.rb" }
  watch('hitTheDot.rb') { "spec/hitTheDot_spec.rb" }
end
